# Generated by Django 5.0 on 2024-04-02 20:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='Image')),
                ('video', models.FileField(blank=True, upload_to='video')),
                ('audio', models.FileField(blank=True, upload_to='video')),
                ('pdf', models.FileField(blank=True, upload_to='video')),
                ('caption', models.TextField(max_length=5000)),
                ('no_of_likes', models.IntegerField(default=0)),
                ('no_of_shares', models.IntegerField(default=0)),
                ('profileimage', models.ImageField(default='blank.png', upload_to='profileImage')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500000, null=True)),
                ('comment', models.CharField(max_length=50000000, null=True)),
                ('ids', models.CharField(max_length=50, null=True)),
                ('profileimage', models.ImageField(default='blank.png', upload_to='')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.post')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('nickname', models.CharField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('level', models.CharField(blank=True, max_length=500)),
                ('profileimage', models.ImageField(default='blank.png', upload_to='profileImage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
