# Generated by Django 5.0 on 2024-04-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_followerscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdf'),
        ),
    ]
