# Generated by Django 5.0 on 2024-04-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_favourite_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite_post',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
