# Generated by Django 5.0 on 2024-04-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_favourite_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favourites',
            field=models.FileField(blank=True, upload_to='favourites'),
        ),
    ]
