# Generated by Django 5.0 on 2024-04-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
