# Generated by Django 5.0 on 2024-04-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_post_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comments',
            new_name='no_of_comments',
        ),
    ]
