# Generated by Django 5.0 on 2024-04-02 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_rename_comments_post_no_of_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='no_of_comments',
        ),
    ]
