# Generated by Django 5.0 on 2024-04-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_remove_post_no_of_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='no_of_commenters',
            field=models.IntegerField(default=0),
        ),
    ]
