# Generated by Django 5.0 on 2024-04-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_post_no_of_commenters'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favourites_text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
