# Generated by Django 5.0 on 2024-04-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_post_favourites_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
