# Generated by Django 5.0 on 2024-04-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_rename_post_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50000000, null=True),
        ),
    ]
