# Generated by Django 5.0 on 2024-04-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
