# Generated by Django 5.0 on 2024-04-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_group_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_comment',
            name='group_name',
            field=models.CharField(max_length=50000000, null=True),
        ),
    ]
