# Generated by Django 5.0 on 2024-04-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_group_comment_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50000000, null=True)),
                ('receiver', models.CharField(max_length=50000000, null=True)),
                ('profileimage', models.ImageField(default='blank.png', upload_to='')),
                ('message', models.CharField(max_length=50000000, null=True)),
            ],
        ),
    ]
