# Generated by Django 5.0 on 2024-04-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_message_receiverid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='senderId',
            field=models.CharField(max_length=50000000, null=True),
        ),
    ]
