# Generated by Django 5.0 on 2024-05-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_message_senderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiverId', models.CharField(max_length=50000000, null=True)),
                ('senderId', models.CharField(max_length=50000000, null=True)),
            ],
        ),
    ]
